# Generated by Django 5.0.1 on 2024-01-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Manager', 'Manager')], default='Member', max_length=55),
        ),
    ]
